### Configuration for dataset generation ###

paths:
  # The full path, including filename, for the output HDF5 dataset.
  output_path: "../datasets/MAXIMA-SWIN_10k_dataset.hdf5"

calibrant: 'alpha_Al2O3'
detector: 'Eiger2Cdte_1M'
wavelength: 0.5121261413149675e-10

geometry_ranges:
  dist: [0.10, 0.15]
  poni1: [0.040, 0.045]
  poni2: [0.035, 0.040]
  rot1: [-0.05, 0.05]
  rot2: [-0.05, 0.05]
  rot3: [-0.05, 0.05]

simulation_ranges:
  fwhm: [0.13, 0.20]
  imin: [2.0, 6.0]
  imax: [150.0, 300.0]

generation:
  num_images: 10000
  test_split_ratio: 0.1